num1 = int(input("Enter Number1:"))
num2 = int(input("Enter Number2:"))
print("%d + %d = %d"%(num1,num2,num1+num2))
print("%d - %d = %d"%(num1,num2,num1-num2))
print("%d * %d = %d"%(num1,num2,num1*num2))
print("%d / %d = %d"%(num1,num2,num1/num2))